import type { LlmRequest, OverviewMetric } from "@/types/observability";

export const overviewMetrics: OverviewMetric[] = [
  {
    label: "Requests",
    value: "1.28M",
    change: 18.4,
    hint: "Across 42 active projects",
    tone: "accent",
  },
  {
    label: "Total cost",
    value: "$18,420",
    change: 7.2,
    hint: "14.3% below budget",
    tone: "success",
  },
  {
    label: "P95 latency",
    value: "1.84s",
    change: -12.6,
    hint: "246ms faster this period",
    tone: "success",
  },
  {
    label: "Error rate",
    value: "0.73%",
    change: -3.1,
    hint: "Within the 1% objective",
    tone: "warning",
  },
];

export const trafficSeries = {
  "24h": [34, 28, 31, 42, 38, 46, 54, 62, 58, 66, 71, 65, 78, 84, 76, 88, 82, 92, 86, 96, 91, 102, 98, 112],
  "7d": [42, 58, 51, 74, 69, 83, 96],
  "30d": [35, 42, 39, 48, 51, 46, 58, 62, 56, 68, 73, 69, 78, 84, 80, 91, 87, 96, 101, 95, 108, 114, 109, 121, 118, 128, 124, 136, 132, 145],
};

export const modelShare = [
  { model: "claude-sonnet-4", provider: "Anthropic", share: 38, cost: "$6,998", color: "#70a7ff" },
  { model: "gpt-5-mini", provider: "OpenAI", share: 27, cost: "$4,973", color: "#5de2a5" },
  { model: "gemini-2.5-pro", provider: "Google", share: 19, cost: "$3,501", color: "#a78bfa" },
  { model: "deepseek-v3", provider: "DeepSeek", share: 10, cost: "$1,842", color: "#f5c76a" },
  { model: "Other models", provider: "7 providers", share: 6, cost: "$1,106", color: "#60708a" },
];

export const requests: LlmRequest[] = [
  {
    id: "req_01JY8E8F9T",
    timestamp: "2026-07-14T13:42:18+08:00",
    model: "claude-sonnet-4",
    provider: "Anthropic",
    project: "Engineering Copilot",
    user: "li.ming@topoai.dev",
    status: "success",
    latencyMs: 1240,
    inputTokens: 18234,
    outputTokens: 2841,
    costUsd: 0.1284,
    cached: true,
    prompt: "Review the release candidate and identify migration risks.",
    response: "The release candidate has three migration risks: schema compatibility, key rotation, and worker replay behavior.",
  },
  {
    id: "req_01JY8E54QH",
    timestamp: "2026-07-14T13:40:51+08:00",
    model: "gpt-5-mini",
    provider: "OpenAI",
    project: "Customer Support",
    user: "support-bot@acme.cn",
    status: "success",
    latencyMs: 842,
    inputTokens: 4520,
    outputTokens: 932,
    costUsd: 0.0216,
    cached: false,
    prompt: "Summarize the customer's open incidents and draft a response.",
    response: "Two incidents remain open. The database timeout is mitigated and the export issue is awaiting validation.",
  },
  {
    id: "req_01JY8DZYCP",
    timestamp: "2026-07-14T13:36:05+08:00",
    model: "gemini-2.5-pro",
    provider: "Google",
    project: "Contract Intelligence",
    user: "chen.yu@acme.cn",
    status: "error",
    latencyMs: 10012,
    inputTokens: 24411,
    outputTokens: 0,
    costUsd: 0.0812,
    cached: false,
    prompt: "Compare these two contract versions and highlight financial changes.",
    response: "Provider timeout before a complete response was received.",
  },
  {
    id: "req_01JY8DVF6A",
    timestamp: "2026-07-14T13:31:43+08:00",
    model: "deepseek-v3",
    provider: "DeepSeek",
    project: "Code Modernization",
    user: "wang.lei@topoai.dev",
    status: "success",
    latencyMs: 2168,
    inputTokens: 31900,
    outputTokens: 4650,
    costUsd: 0.0342,
    cached: true,
    prompt: "Convert this legacy data access layer to a repository abstraction.",
    response: "Created repository interfaces, transaction boundaries, and a migration plan for existing callers.",
  },
  {
    id: "req_01JY8DR1MB",
    timestamp: "2026-07-14T13:27:22+08:00",
    model: "claude-sonnet-4",
    provider: "Anthropic",
    project: "Finance Analyst",
    user: "finance-agent@acme.cn",
    status: "rate_limited",
    latencyMs: 124,
    inputTokens: 0,
    outputTokens: 0,
    costUsd: 0,
    cached: false,
    prompt: "Build the weekly cost variance explanation.",
    response: "Project RPM limit exceeded. Retry after 24 seconds.",
  },
  {
    id: "req_01JY8DMN8R",
    timestamp: "2026-07-14T13:22:14+08:00",
    model: "gpt-5-mini",
    provider: "OpenAI",
    project: "Knowledge Search",
    user: "zhao.xin@acme.cn",
    status: "success",
    latencyMs: 734,
    inputTokens: 8120,
    outputTokens: 651,
    costUsd: 0.0189,
    cached: true,
    prompt: "Find the deployment policy for regulated customer environments.",
    response: "Regulated deployments require private networking, customer-managed keys, and quarterly restore validation.",
  },
];

