import type { VaultAccessEvent, VaultSecret } from "@/types/vault";

export const seedVaultSecrets: VaultSecret[] = [
  { id: "vsec_openai_primary", organizationId: "org_topoai", name: "OpenAI Primary API Key", kind: "provider_api_key", scopeType: "provider", scopeId: "provider_openai_primary", status: "active", reference: "vault://org_topoai/vsec_openai_primary", maskedValue: "sk-p••••••••MOCK", fingerprint: "5ddcfaa6c7e3153c", currentVersion: 2, rotationIntervalDays: 90, lastRotatedAt: "2026-06-15T02:00:00Z", rotationDueAt: "2026-09-13T02:00:00Z", expiresAt: null, createdBy: "holden@topoai.dev", createdAt: "2026-03-17T02:00:00Z", updatedAt: "2026-06-15T02:00:00Z", disabledAt: null, disabledBy: "", disabledReason: "" },
  { id: "vsec_anthropic_primary", organizationId: "org_topoai", name: "Anthropic Primary API Key", kind: "provider_api_key", scopeType: "provider", scopeId: "provider_anthropic_primary", status: "active", reference: "vault://org_topoai/vsec_anthropic_primary", maskedValue: "sk-a••••••••MOCK", fingerprint: "bb83e6bf797c84e6", currentVersion: 1, rotationIntervalDays: 60, lastRotatedAt: "2026-05-01T02:00:00Z", rotationDueAt: "2026-06-30T02:00:00Z", expiresAt: null, createdBy: "security@topoai.dev", createdAt: "2026-05-01T02:00:00Z", updatedAt: "2026-05-01T02:00:00Z", disabledAt: null, disabledBy: "", disabledReason: "" },
  { id: "vsec_slack_legacy", organizationId: "org_topoai", name: "Legacy Slack Bot Token", kind: "integration_token", scopeType: "notification", scopeId: "slack_legacy", status: "disabled", reference: "vault://org_topoai/vsec_slack_legacy", maskedValue: "xoxb••••••••MOCK", fingerprint: "2512f31323f2aee4", currentVersion: 1, rotationIntervalDays: 90, lastRotatedAt: "2026-02-01T02:00:00Z", rotationDueAt: "2026-05-02T02:00:00Z", expiresAt: null, createdBy: "security@topoai.dev", createdAt: "2026-02-01T02:00:00Z", updatedAt: "2026-06-01T02:00:00Z", disabledAt: "2026-06-01T02:00:00Z", disabledBy: "security@topoai.dev", disabledReason: "Connector retired" },
];

export const seedVaultAccessEvents: VaultAccessEvent[] = [
  { id: "vacc_provider_health", organizationId: "org_topoai", secretId: "vsec_openai_primary", secretName: "OpenAI Primary API Key", secretVersion: 2, actor: "provider-health-worker", workload: "provider-health-worker", purpose: "active provider probe", outcome: "success", requestId: "probe_openai_20260715", sourceIp: "10.20.0.12", errorCode: "", createdAt: "2026-07-15T01:00:00Z" },
  { id: "vacc_rotation", organizationId: "org_topoai", secretId: "vsec_openai_primary", secretName: "OpenAI Primary API Key", secretVersion: 2, actor: "holden@topoai.dev", workload: "control-plane", purpose: "rotate secret: scheduled rotation", outcome: "success", requestId: "req_vault_rotate_001", sourceIp: "10.12.0.8", errorCode: "", createdAt: "2026-06-15T02:00:00Z" },
];
