BEGIN;

DROP TABLE IF EXISTS audit_exports;
DROP TABLE IF EXISTS audit_retention_policies;
DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS vault_access_events;
DROP TABLE IF EXISTS vault_secret_versions;
DROP TABLE IF EXISTS vault_secrets;
DROP TABLE IF EXISTS api_key_models;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS routing_targets;
DROP TABLE IF EXISTS notification_deliveries;
DROP TABLE IF EXISTS notification_escalation_policies;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS notification_preferences;
DROP TABLE IF EXISTS report_runs;
DROP TABLE IF EXISTS report_schedules;
DROP TABLE IF EXISTS webhook_deliveries;
DROP TABLE IF EXISTS webhook_endpoints;
DROP TABLE IF EXISTS alert_incidents;
DROP TABLE IF EXISTS alert_rules;
DROP TABLE IF EXISTS budgets;
DROP TABLE IF EXISTS rate_limit_rules;
DROP TABLE IF EXISTS routing_policies;
DROP TABLE IF EXISTS models;
DROP TABLE IF EXISTS provider_health_events;
DROP TABLE IF EXISTS provider_health_probes;
DROP TABLE IF EXISTS provider_connections;
DROP TABLE IF EXISTS role_bindings;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS workspaces;
DROP TABLE IF EXISTS organizations;
DELETE FROM schema_migrations WHERE version = 1;
DROP FUNCTION IF EXISTS prevent_audit_event_mutation();
DROP FUNCTION IF EXISTS prevent_vault_access_event_mutation();
DROP FUNCTION IF EXISTS set_updated_at();

COMMIT;
